project:
  type: book

book:
  title: "Investigación sobre Accesibilidad"
  subtitle: "PSWE-04 Diseño de Software"
  author:
    - Daniel Canessa Valverde
    - Stephanie Delgado Brenes
  date: "2025-07-18"
  chapters:
    - index.qmd
    - 01-introduccion.qmd
    - 02-objetivos.qmd
    - 03-accesibilidad.qmd
    - 04-tecnologias.qmd
    - 05-estandares.qmd
    - 06-barreras-comunes.qmd
    - 07-buenas-practicas.qmd
    - 08-conclusiones.qmd
    - references.qmd

bibliography: references.bib
csl: ieee.csl

format:
  pdf:
    documentclass: scrreprt
